[package]
name = "quant-core"
version.workspace = true
edition.workspace = true

[dependencies]
# ğŸ‘‡ å¿…é¡»è¦æœ‰è¿™ä¸¤è¡Œï¼ŒIDE æ‰èƒ½è¯†åˆ« rust_decimal
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
strum = { workspace = true }